name: Deploy
on:
    workflow_dispatch: {}
    push:
        branches:
            - main

permissions:
    contents: write
    pages: write
    id-token: write

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: Build & Deploy
        environment:
            name: github-pages
            url: ${{ steps.deployment.outputs.page_url }}
        steps:
            - uses: actions/checkout@v3
              with:
                  fetch-depth: 0
            - uses: actions/setup-node@v3
              with:
                  node-version: 18
            - run: npm install
            - name: Build
              run: npm run build
            - uses: actions/configure-pages@v2
            - uses: actions/upload-pages-artifact@v1
              with:
                  path: .vitepress/dist
            - name: Deploy
              id: deployment
              uses: actions/deploy-pages@v1
            - name: Push
              uses: s0/git-publish-subdir-action@develop
              env:
                  REPO: self
                  BRANCH: build
                  FOLDER: .vitepress/dist
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
                  MESSAGE: "Build: ({sha}) {msg}"
